[package]
name = "dart-ffi"
version = "0.1.0"
edition = "2021"

[dependencies]
http-lib = { path = "../http-lib" }
error-lib = { path = "../error-lib" }
prost = "0.12"

[lib]
name = "dart_ffi"
crate-type = ["cdylib", "staticlib"]