/* Generated by cbindgen for Simple FFI */

#ifndef SIMPLE_FFI_H
#define SIMPLE_FFI_H

#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

double simple_add(double a,
                  double b);

double simple_multiply(double a,
                       double b);

char *simple_greet(const char *name);

void free_string(char *s);

char *test_greet(const char *name);

#endif  /* SIMPLE_FFI_H */
