/* Generated by cbindgen for Simple FFI */

#ifndef SIMPLE_FFI_H
#define SIMPLE_FFI_H

#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

char *login(const uint8_t *request_bytes,
            uintptr_t request_len);

void free_string(char *ptr);

#endif  /* SIMPLE_FFI_H */
